### ISSUE TITLE
Issue when login with an expired JWT token

### ISSUE THREAD

**Issue by HenriChabert** [nabla/nabla-ios#1]
Hello team,

I am trying to integrate Nabla into a React Native application and I am facing some issues doing it, although I am using the tutorial there: https://github.com/nabla/nabla-react-native/tree/main/messaging-sample-app.

Using exactly this code, it seems that, once the JWT token get's expired, it cannot be refreshed even though we provide the refresh token. I get the following message running the app onto a real device: 
```
Apollo.WebSocket.WSError.ErrorType.protocolError, message: \"401 - HTTP_UNAUTHORIZED: Invalid JWT token: The Token has expired on Mon May 08 17:27:04 GMT 2023.\", code: 1002)"
```

The problem is that is is rather not predictable, it sometimes work, sometimes it fails with the following messages:
```
[Nabla-SDK] Failed to mark conversation as seen
error: 
{
  "extra": {
    "reason": null
  }
}
``` 
or 
```
[Nabla-SDK] Failed to set is typing
error: 
{
  "extra": {
    "reason": null
  }
}
```

Furthermore, when initializing the app, it seems that the tokens are not retrieved when it needs. For example, when I connect with two different users, even though we initialized the app with the first user, when switching to the second one, it seems that the aut tokens are not retrieved again although it should because the tokens for the new users have changed.

I have ran the tests on both iOS simulators (iPhone 12, iPhone 14, iPad) and real device (iPhone 12 Mini). I am running under iOS 16.2.

If you need any other information, please do not hesitate. It is pretty hard to give more because the error messages are not really self explanatory but I can run other tests on my side to bring precision.

**Comment by tgyhlsb** [comment]
Hi @HenriChabert 

Thanks for your feedback, we'll investigate your issue.

Are you doing anything specific with your app when the issue happens? Like sending it to background or turning the network off?

> Furthermore, when initializing the app, it seems that the tokens are not retrieved when it needs. For example, when I connect with two different users, even though we initialized the app with the first user, when switching to the second one, it seems that the aut tokens are not retrieved again although it should because the tokens for the new users have changed.

What do you mean by "tokens are not retrieved" here? If you authenticate with valid tokens, the SDK does not need to refresh the tokens, it should call `SessionTokenProvider.provideTokens` tho.

**Comment by alacoste** [comment]
We have identified the root cause of the issue, and a fix was deployed. Because the problem was entirely with our infra & backend, you don't need to change anything, and should be able to test the fix already!

More details about the issue: because of a cache mis-configuration, the JWT refresh request was not being routed to the correct datacenter for your organization. As a result, the SDK was unable to refresh the JWT access token in time and ends up using the expired one.

**Comment by HenriChabert** [comment]
Hello @alacoste, thanks for this quick fix, seems to work a lot better know!

**Comment by alacoste** [comment]
> Hello @alacoste, thanks for this quick fix, seems to work a lot better know!

@HenriChabert my pleasure, don't hesitate if you run into other issues!

**Comment by HenriChabert** [comment]
Hello @alacoste,
I am still getting some errors using React Native Nabla component:
```
 WARN  [Nabla-SDK] Failed to watch conversation
error: 
{}
 WARN  [Nabla-SDK] Failed to watch messages
error: 
{}
```
I verified that the conversation and Nabla ID are defined properly. Any way I could investigate deeper on the error to help you debug this?

In case you have some logs on your side, the errors have happened between 22h55 and 23h00 today.

Thanks!

**Comment by tgyhlsb** [comment]
Hi @HenriChabert,
Sad to here the news, this might be related to other reports we have around `setCurrentUserOrThrow(userId)`. This method must be called at least once before being able to use the SDK, even if the user was already logged in but then killed the app to restart it.
Can you check that it is the case for you?

**Comment by HenriChabert** [comment]
Hi @tgyhlsb!
I am using the method `getCurrentUserId`. If this function returns a valid ID that corresponds to the current user, do we still need to call `setCurrentUserOrThrow`?
It seems that calling this function when a user Is already logged in indeed kills the app.

**Comment by HenriChabert** [comment]
So I have indeed ran a bunch of tests on the problem of the app crashing, and the error we get from Xcode is the following:
```
Thread 112: "Error when sending event: needProvideTokens with body: {\n    userId = \"8780b31a-0e90-4bd6-bf77-e6f35c4451af\";\n}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in NablaClientModule, even though it's inherited from RCTEventEmitter."
```

**Comment by benoitletondor** [comment]
Hey @HenriChabert .

We just released version `1.1.3` on NPM that should fix both issues:
- The crash you reported on https://github.com/nabla/nabla-ios/issues/1#issuecomment-1555001322
- You don't need to call `setCurrentUserOrThrow` again if `getCurrentUserId` returns the correct userId for you

Let us know how it goes

**Comment by HenriChabert** [comment]
Hello @benoitletondor,

Thanks for this quick fix! Just checked and tested it, and it indeed seems to work perfectly!

Small suggestions would now be to integrate the push notifications (I went through FCM and webhook which works pretty well but having a native integration would be awesome!)

Thanks again

**Comment by HenriChabert** [comment]
Hello team,

After updating the package to 1.1.3, Nabla still crashes the app.
Here is the error I get when using Nabla component:

```
2023-05-24 09:50:04.888880+0200 moonalisaAlpha[18817:1318042] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: needProvideTokens with body: {
    userId = "8780b31a-0e90-4bd6-bf77-e6f35c4451af";
}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in NablaClientModule, even though it's inherited from RCTEventEmitter.'
*** First throw call stack:
(0x1874bed94 0x18057c3d0 0x181c71808 0x103cc8c34 0x10471487c 0x1047148ac 0x10387b4d4 0x1918268d0 0x19182691c 0x1918264e0 0x1918262f9 0x10387a5b1 0x103878e81 0x1038795dd 0x103916fb9 0x10391738d 0x191868dd9)
libc++abi: terminating due to uncaught exception of type NSException
``` 
Any idea how I could fix that?
Thanks!

**Comment by benoitletondor** [comment]
Hey, thanks for following up.

Can you give us your precise runtime that leads to that crash? I'm not reproducing this and we never got any other reports of that crash so we need to have more info.

**Comment by benoitletondor** [comment]
I'm closing this issue as it's not related to the original topic nor the iOS SDK. Please come back to us on the react-native repo if you have anything. Thanks
